### ISSUE TITLE
Unary operator expected during --update as super user

### ISSUE THREAD

**Issue by umasse** [brunelli/gnome-shell-extension-installer#10]
Hi,
I just found your script, and it seems exactly what I was looking for.
I have noticed this error message (second line):

> [auto-move-windows@gnome-shell-extensions.gcampax.github.com] Searching extensions.gnome.org
> ./gnome-shell-extension-installer: line 75: [: 32: unary operator expected
> [Auto Move Windows] New version available
> [Auto Move Windows] Downloading extension
> [Auto Move Windows] Extracting extension

When I ran the --update as superuser, it seems to have updated all the extensions, while according to the web interface, only 3 needed it. So it seems that error causes the script to detect all extensions as needing update.
Other than that, great work!

**Comment by brunelli** [comment]
I may have an idea of what the problem is...

Could you please send the output of `bash --version` and `sed --version` in here?

**Comment by umasse** [comment]
Sure, here you go (without extra lines):
> $ bash  --version
> GNU bash, version 4.4.7(1)-release (x86_64-pc-linux-gnu)
> $ sed --version
> sed (GNU sed) 4.4

**Comment by brunelli** [comment]
The error is due to the fact that extensions installed via a package manager (usually?) don't have a version number on their `metadata.json` file, as this is added by EGO. That's why the error only occurs when running as root (extensions in `/usr/share/gnome-shell/extensions/` are usually installed via a package manager).

I thought it would be better to just throw an error saying "use your package manager to update this extension" when we are unable to find the version number, instead of trying to do something, and that's what the following commit will implement.

Thank you very much for the report and the help!
